name: Build

on:
  push:
    branches: [typescript]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Building...
        run: |
          yarn build
          yarn build:docs
